name: sentiment-analysis-v08
services:
  # postgres:
  #   image: postgres:13
  #   container_name: postgres-sentiment-analysis
  #   environment:
  #     - POSTGRES_DB=database
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - monitoring-network

  # rabbitmq:
  #   image: rabbitmq:3.12-management
  #   container_name: rabbitmq-sentiment-analysis
  #   ports:
  #     - "5672:5672"  
  #     - "15672:15672"  
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   networks:
  #     - monitoring-network

  prometheus:
    image: docker.io/prom/prometheus:v3.1.0 # Changed to 'latest' for simplicity or specify a desired version
    container_name: prometheus-v08
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus" # Added storage path
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus:/prometheus
    restart: unless-stopped
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:latest
    container_name: loki-v08
    volumes:
      - ./configs/loki.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki:rw
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - monitoring-network

  grafana:
    image: docker.io/grafana/grafana-oss:11.5.1
    container_name: grafana-v08
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring-network

  celery-exporter:
    image: danihodovic/celery-exporter
    ports:
      - "9808:9808"
    env_file:
      - ./consumer/.env
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - monitoring-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: sentiment-analysis-consumer-v08
    env_file:
      - ./consumer/.env
    # depends_on:
    #   - postgres
    #   - rabbitmq
    networks:
      - monitoring-network

  # sentiment-analysis:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: sentiment-analysis-server-v08
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./backend/.env
  #   # depends_on:
  #   #   - postgres
  #   #   - rabbitmq
  #   networks:
  #     - monitoring-network

volumes:
  prometheus:
  grafana:
  data_loki:
    driver: local

networks:
  monitoring-network:
    driver: bridge