{
 "title": "Celery / Tasks / By Task",
 "description": "A dashboard that monitors Celery. It is created using the Celery-mixin for the the (Celery-exporter)[https://github.com/danihodovic/celery-exporter]",
 "tags": [
  "celery",
  "celery-mixin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_worker_up{}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(celery_worker_up{namespace=\"$namespace\"}, job)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{namespace=\"$namespace\", job=\"$job\", name!~\"None\"}, queue_name)"
   },
   {
    "name": "task",
    "label": "Task",
    "query": "label_values(celery_task_received_total{namespace=\"$namespace\", job=\"$job\", queue_name=~\"$queue_name\", name!~\"None\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Task Duration (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_runtime_sum{}[1m]))\r\n/\r\nsum by (name) (rate(celery_task_runtime_count{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "avg(celery_queue_length{})", "legendFormat": "Length" }
   ]
  },
  {
   "title": "Received tasks total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(celery_task_received_total{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average Task Duration (10m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_runtime_sum{}[10m]))\r\n/\r\nsum by (name) (rate(celery_task_runtime_count{}[10m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Task Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n/(sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n+sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n) > -1\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    }
   ]
  },
  {
   "title": "Task Exceptions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  ) by (name, exception) > 0\n)\n"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Succeeded - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Failed - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Sent - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Received - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Retried - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Revoked - {{ name }}"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name) > 0\n",
     "legendFormat": "Rejected - {{ name }}"
    }
   ]
  },
  {
   "title": "Task Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    )\n  )\n) by (name, exception) > 0\n",
     "legendFormat": "{{ name }}/{{ exception }}"
    }
   ]
  },
  {
   "title": "Tasks Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P50 - {{ name }}"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P95 - {{ name }}"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      celery_task_runtime_bucket{\n        job=\"$job\",\n        name=~\"$task\",\n        queue_name=~\"$queue_name\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (name, job, le)\n)\n",
     "legendFormat": "P99 - {{ name }}"
    }
   ]
  }
 ]
}