{
 "title": "FastAPI Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/metrics|/metrics/\"}[30s]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_total{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "2xx Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_request_total{instance=\"sentiment-analysis:8000\", path!~\"/metrics\", status=~\"2..\"}[$__range])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "4xx Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_request_total{instance=\"sentiment-analysis:8000\", path!~\"/metrics|/favicon.ico\", status=~\"4..\"}[$__range])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, http_request_duration_seconds_sum{path!~\"/metrics\", status=\"201\"} / http_request_duration_seconds_count{path!~\"/metrics\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_total{instance=\"sentiment-analysis:8000\", path!~\"/metrics\"}[1m])",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"200\", path=~\"/metrics\"}[60m])) / sum(rate(http_request_total{path=~\"/metrics\"}[60m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{status=\"4..\"}[60m])) / sum(rate(http_request_total[60m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "P99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "P90 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.90,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "P50 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.50,sum(rate(http_request_duration_seconds_bucket{instance=\"sentiment-analysis:8000\", path!=\"/metrics\"}[$__rate_interval])) by(path, method, le))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "Request/Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(request_size_bytes_sum[5m]) / rate(request_size_bytes_count[5m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(rate(response_size_bytes_sum[5m]) / rate(response_size_bytes_count[5m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Request/Response size Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_size_bytes_bucket[$__rate_interval]))",
     "legendFormat": "Request"
    },
    {
     "expr": "histogram_quantile(0.95, rate(response_size_bytes_bucket[$__rate_interval]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{status=~\"2..\", path!~\"/metrics\"}[30s])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Queries Per Second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(db_request_duration_seconds_count{}[$__rate_interval]) )",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Database Insert Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_request_duration_seconds_bucket{}[30s])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{severity=\"error\"}"
    }
   ]
  },
  {
   "title": "Info and others",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"fastapi\", severity!=\"error\"}"
    }
   ]
  },
  {
   "title": "Total number of logs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"fastapi\"} [$__auto])) by (detected_level)"
    }
   ]
  }
 ]
}