---
global:
  scrape_interval: 5s # By default, scrape targets every 5 seconds.

scrape_configs:
  - job_name: "server"
    static_configs:
      - targets: ["sentiment-analysis:8000"]
        # - targets: ["host.docker.internal:8000"]
        labels:
          service: "server"

  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["node_exporter:9100"]

  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8080"]
  #       labels:
  #         service: "cadvisor"
